<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FicheDescriptiveSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fiche_descriptives')->insert([
            [
                'dateCreation' => '2024-01-01',
                'dateDerniereModification' => '2024-01-01',
                'contenuStage' => 'Développement d\'une application web',
                'thematique' => 'Développement web',
                'sujet' => 'Développement d\'une application web',
                'fonctions' => 'Développeur web',
                'taches' => 'Développement d\'une application web',
                'competences' => 'Connaissances en WebDev',
                'details' => 'Développement d\'une application web',
                'debutStage' => '2024-01-01',
                'finStage' => '2024-06-30',
                'nbJourSemaine' => 5,
                'nbHeureSemaine' => 35,
                'clauseConfidentialite' => 1,
                'serviceEntreprise' => 'Service informatique',
                'adresseMailStage' => 'perigueux@zero-infini.fr',
                'telephoneStage' => '0556090807',
                'adresseStage' => '20 Rue Ernest Guillier',
                'codePostalStage' => '24000',
                'villeStage' => 'Périgueux',
                'paysStage' => 'France',
                'longitudeStage' => '0.716667',
                'latitudeStage' => '45.183333',
                'statut' => 'En cours',
                'numeroConvention' => '37629',
                'interruptionStage' => 0,
                'dateDebutInterruption' => null,
                'dateFinInterruption' => null,
                'personnelTechniqueDisponible' => 1,
                'materielPrete' => 'Ordinateur, écrans, souris, clavier',
                'idEntreprise' => 1,
                'idTuteurEntreprise' => 1,
                'idUPPA' => '610000',
            ],
            [
                'dateCreation' => '2024-01-01',
                'dateDerniereModification' => '2024-01-01',
                'contenuStage' => 'Développement d\'une application web',
                'thematique' => 'Développement web',
                'sujet' => 'Développement d\'une application web',
                'fonctions' => 'Développeur web',
                'taches' => 'Développement d\'une application web',
                'competences' => 'Connaissances en WebDev',
                'details' => 'Développement d\'une application web',
                'debutStage' => '2024-01-01',
                'finStage' => '2024-06-30',
                'nbJourSemaine' => 5,
                'nbHeureSemaine' => 35,
                'clauseConfidentialite' => 1,
                'serviceEntreprise' => 'Service informatique',
                'adresseMailStage' => 'perigueux@zero-infini.fr',
                'telephoneStage' => '0556090807',
                'adresseStage' => '20 Rue Ernest Guillier',
                'codePostalStage' => '24000',
                'villeStage' => 'Périgueux',
                'paysStage' => 'France',
                'longitudeStage' => '0.716667',
                'latitudeStage' => '45.183333',
                'statut' => 'En cours',
                'numeroConvention' => '37629',
                'interruptionStage' => 0,
                'dateDebutInterruption' => null,
                'dateFinInterruption' => null,
                'personnelTechniqueDisponible' => 1,
                'materielPrete' => 'Ordinateur, écrans, souris, clavier',
                'idEntreprise' => 1,
                'idTuteurEntreprise' => 1,
                'idUPPA' => '583303',
            ],
            [
                'dateCreation' => '2024-01-01',
                'dateDerniereModification' => '2024-01-01',
                'contenuStage' => 'Développement d\'une application web',
                'thematique' => 'Développement web',
                'sujet' => 'Développement d\'une application web',
                'fonctions' => 'Développeur web',
                'taches' => 'Développement d\'une application web',
                'competences' => 'Connaissances en WebDev',
                'details' => 'Développement d\'une application web',
                'debutStage' => '2024-01-01',
                'finStage' => '2024-06-30',
                'nbJourSemaine' => 5,
                'nbHeureSemaine' => 35,
                'clauseConfidentialite' => 1,
                'serviceEntreprise' => 'Service informatique',
                'adresseMailStage' => 'bordeaux@cgi.fr',
                'telephoneStage' => '0556010203',
                'adresseStage' => '6 Rue des cometes',
                'codePostalStage' => '33185',
                'villeStage' => 'Le haillan',
                'paysStage' => 'France',
                'longitudeStage' => '-0.666667',
                'latitudeStage' => '44.833333',
                'statut' => 'Validee',
                'numeroConvention' => '39205',
                'interruptionStage' => 0,
                'dateDebutInterruption' => null,
                'dateFinInterruption' => null,
                'personnelTechniqueDisponible' => 1,
                'materielPrete' => 'Ordinateur, écrans, souris, clavier',
                'idEntreprise' => 2,
                'idTuteurEntreprise' => 2,
                'idUPPA' => '610001',
            ],
            [
                'dateCreation' => '2024-01-01',
                'dateDerniereModification' => '2024-01-01',
                'contenuStage' => 'Développement d\'une application web',
                'thematique' => 'Développement web',
                'sujet' => 'Développement d\'une application web',
                'fonctions' => 'Développeur web',
                'taches' => 'Développement d\'une application web',
                'competences' => 'Connaissances en WebDev',
                'details' => 'Développement d\'une application web',
                'debutStage' => '2024-01-01',
                'finStage' => '2024-06-30',
                'nbJourSemaine' => 5,
                'nbHeureSemaine' => 35,
                'clauseConfidentialite' => 1,
                'serviceEntreprise' => 'Service informatique',
                'adresseMailStage' => 'info@iutbayonne.univ-pau.fr',
                'telephoneStage' => '0559010203',
                'adresseStage' => '2 allée du Parc Montaury',
                'codePostalStage' => '64600',
                'villeStage' => 'Anglet',
                'paysStage' => 'France',
                'longitudeStage' => '-1.50939',
                'latitudeStage' => '43.47977',
                'statut' => 'Validee',
                'numeroConvention' => '37680',
                'interruptionStage' => 0,
                'dateDebutInterruption' => null,
                'dateFinInterruption' => null,
                'personnelTechniqueDisponible' => 1,
                'materielPrete' => 'Ordinateur, écrans, souris, clavier',
                'idEntreprise' => 7,
                'idTuteurEntreprise' => 7,
                'idUPPA' => '610123'
            ],
            [
                'dateCreation' => '2024-01-01',
                'dateDerniereModification' => '2024-01-01',
                'contenuStage' => 'Développement d\'une application web',
                'thematique' => 'Développement web',
                'sujet' => 'Développement d\'une application web',
                'fonctions' => 'Développeur web',
                'taches' => 'Développement d\'une application web',
                'competences' => 'Connaissances en WebDev',
                'details' => 'Développement d\'une application web',
                'debutStage' => '2024-01-01',
                'finStage' => '2024-06-30',
                'nbJourSemaine' => 5,
                'nbHeureSemaine' => 35,
                'clauseConfidentialite' => 1,
                'serviceEntreprise' => 'Service informatique',
                'adresseMailStage' => 'bordeaux@cgi.fr',
                'telephoneStage' => '0556010203',
                'adresseStage' => '6 Rue des cometes',
                'codePostalStage' => '33185',
                'villeStage' => 'Le haillan',
                'paysStage' => 'France',
                'longitudeStage' => '-0.666667',
                'latitudeStage' => '44.833333',
                'statut' => 'Validee',
                'numeroConvention' => '37640',
                'interruptionStage' => 0,
                'dateDebutInterruption' => null,
                'dateFinInterruption' => null,
                'personnelTechniqueDisponible' => 1,
                'materielPrete' => 'Ordinateur, écrans, souris, clavier',
                'idEntreprise' => 2,
                'idTuteurEntreprise' => 2,
                'idUPPA' => '610124'
            ]
        ]);
    }
}
