sonar.projectKey=Gestion-des-stages
sonar.projectName=Gestion-des-stages
sonar.host.url=http://localhost:9000
sonar.login=sqp_4c0ffc1eebce634c310ee4f7d604e3b089a9e296

# Analyse multi-dossiers
sonar.sources=php/angular/appli-test/src,php/laravel

# Exclusions (important)
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**

# (optionnel selon techno)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml