Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Console\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Console-Kernel.html"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Aschedule\u0028\u0029",
            "name": "schedule",
            "summary": "Define\u0020the\u0020application\u0027s\u0020command\u0020schedule.",
            "url": "classes/App-Console-Kernel.html#method_schedule"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Acommands\u0028\u0029",
            "name": "commands",
            "summary": "Register\u0020the\u0020commands\u0020for\u0020the\u0020application.",
            "url": "classes/App-Console-Kernel.html#method_commands"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler",
            "name": "Handler",
            "summary": "",
            "url": "classes/App-Exceptions-Handler.html"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020the\u0020exception\u0020handling\u0020callbacks\u0020for\u0020the\u0020application.",
            "url": "classes/App-Exceptions-Handler.html#method_register"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontReport",
            "name": "dontReport",
            "summary": "A\u0020list\u0020of\u0020the\u0020exception\u0020types\u0020that\u0020are\u0020not\u0020reported.",
            "url": "classes/App-Exceptions-Handler.html#property_dontReport"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontFlash",
            "name": "dontFlash",
            "summary": "A\u0020list\u0020of\u0020the\u0020inputs\u0020that\u0020are\u0020never\u0020flashed\u0020for\u0020validation\u0020exceptions.",
            "url": "classes/App-Exceptions-Handler.html#property_dontFlash"
        },                {
            "fqsen": "\\App\\Exports\\AffectationsExport",
            "name": "AffectationsExport",
            "summary": "",
            "url": "classes/App-Exports-AffectationsExport.html"
        },                {
            "fqsen": "\\App\\Exports\\AffectationsExport\u003A\u003Aheadings\u0028\u0029",
            "name": "headings",
            "summary": "",
            "url": "classes/App-Exports-AffectationsExport.html#method_headings"
        },                {
            "fqsen": "\\App\\Exports\\BaseExport",
            "name": "BaseExport",
            "summary": "",
            "url": "classes/App-Exports-BaseExport.html"
        },                {
            "fqsen": "\\App\\Exports\\BaseExport\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Exports-BaseExport.html#method___construct"
        },                {
            "fqsen": "\\App\\Exports\\BaseExport\u003A\u003Acollection\u0028\u0029",
            "name": "collection",
            "summary": "",
            "url": "classes/App-Exports-BaseExport.html#method_collection"
        },                {
            "fqsen": "\\App\\Exports\\BaseExport\u003A\u003Aheadings\u0028\u0029",
            "name": "headings",
            "summary": "",
            "url": "classes/App-Exports-BaseExport.html#method_headings"
        },                {
            "fqsen": "\\App\\Exports\\BaseExport\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/App-Exports-BaseExport.html#property_data"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffectationEnseignantController",
            "name": "AffectationEnseignantController",
            "summary": "",
            "url": "classes/App-Http-Controllers-AffectationEnseignantController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffectationEnseignantController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020affectations\u0020existantes",
            "url": "classes/App-Http-Controllers-AffectationEnseignantController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffectationEnseignantController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020affectation",
            "url": "classes/App-Http-Controllers-AffectationEnseignantController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffectationEnseignantController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020une\u0020affectation\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-AffectationEnseignantController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffectationEnseignantController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Met\u0020\u00E0\u0020jour\u0020une\u0020affectation\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-AffectationEnseignantController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffectationEnseignantController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020affectation\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-AffectationEnseignantController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffectationEnseignantController\u003A\u003AextractStudentTeacherAssignments\u0028\u0029",
            "name": "extractStudentTeacherAssignments",
            "summary": "Exporte\u0020les\u0020affectations\u0020de\u0020l\u0027ann\u00E9e\u0020universitaire\u0020courante\u0020en\u0020Excel",
            "url": "classes/App-Http-Controllers-AffectationEnseignantController.html#method_extractStudentTeacherAssignments"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlgorithmeController",
            "name": "AlgorithmeController",
            "summary": "",
            "url": "classes/App-Http-Controllers-AlgorithmeController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlgorithmeController\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Execute\u0020the\u0020algorithm",
            "url": "classes/App-Http-Controllers-AlgorithmeController.html#method_run"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlgorithmeController\u003A\u003AgetTeachers\u0028\u0029",
            "name": "getTeachers",
            "summary": "R\u00E9cup\u00E8re\u0020tous\u0020les\u0020enseignants",
            "url": "classes/App-Http-Controllers-AlgorithmeController.html#method_getTeachers"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlgorithmeController\u003A\u003AgetStudentsForFormationYear\u0028\u0029",
            "name": "getStudentsForFormationYear",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020\u00E9tudiants\u0020d\u0027une\u0020ann\u00E9e\u0020de\u0020formation\u0020sp\u00E9cifique\net\u0020d\u0027une\u0020ann\u00E9e\u0020universitaire\u0020donn\u00E9e",
            "url": "classes/App-Http-Controllers-AlgorithmeController.html#method_getStudentsForFormationYear"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AlgorithmeController\u003A\u003ArunPlanning\u0028\u0029",
            "name": "runPlanning",
            "summary": "",
            "url": "classes/App-Http-Controllers-AlgorithmeController.html#method_runPlanning"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeFormationController",
            "name": "AnneeFormationController",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnneeFormationController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeFormationController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020Ann\u00E9es\u0020de\u0020formation",
            "url": "classes/App-Http-Controllers-AnneeFormationController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeFormationController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020ann\u00E9e\u0020de\u0020formation",
            "url": "classes/App-Http-Controllers-AnneeFormationController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeFormationController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020une\u0020ann\u00E9e\u0020de\u0020formation\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-AnneeFormationController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeFormationController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020une\u0020ann\u00E9e\u0020de\u0020formation\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-AnneeFormationController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeFormationController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020ann\u00E9e\u0020de\u0020formation\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-AnneeFormationController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeUniversitaireController",
            "name": "AnneeUniversitaireController",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnneeUniversitaireController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeUniversitaireController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020ann\u00E9es\u0020universitaires\u0020existantes",
            "url": "classes/App-Http-Controllers-AnneeUniversitaireController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeUniversitaireController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020ann\u00E9e\u0020universitaire",
            "url": "classes/App-Http-Controllers-AnneeUniversitaireController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeUniversitaireController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020une\u0020ann\u00E9e\u0020universitaire\u0020particulier",
            "url": "classes/App-Http-Controllers-AnneeUniversitaireController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeUniversitaireController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020une\u0020ann\u00E9e\u0020universitaire\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-AnneeUniversitaireController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnneeUniversitaireController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020ann\u00E9e\u0020universitaire\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-AnneeUniversitaireController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController",
            "name": "AuthController",
            "summary": "",
            "url": "classes/App-Http-Controllers-AuthController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020informations\u0020de\u0020l\u0027utilisateur\u0020authentifi\u00E9\u0020\u00E0\u0020partir\u0020des\u0020cookies.",
            "url": "classes/App-Http-Controllers-AuthController.html#method_getUser"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EntrepriseController",
            "name": "EntrepriseController",
            "summary": "",
            "url": "classes/App-Http-Controllers-EntrepriseController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EntrepriseController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020entreprises",
            "url": "classes/App-Http-Controllers-EntrepriseController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EntrepriseController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-EntrepriseController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EntrepriseController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020entreprise",
            "url": "classes/App-Http-Controllers-EntrepriseController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EntrepriseController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020une\u0020entreprise\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-EntrepriseController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EntrepriseController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-EntrepriseController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EntrepriseController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020une\u0020entreprise\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-EntrepriseController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EntrepriseController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020entreprise\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-EntrepriseController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantAnneeformAnneeunivController",
            "name": "EtudiantAnneeformAnneeunivController",
            "summary": "",
            "url": "classes/App-Http-Controllers-EtudiantAnneeformAnneeunivController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantAnneeformAnneeunivController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020relations\u0020\u00E9tudiant\u0020\/\u0020ann\u00E9e\u0020de\u0020formation\u0020\/\u0020ann\u00E9e\u0020universitaire",
            "url": "classes/App-Http-Controllers-EtudiantAnneeformAnneeunivController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantAnneeformAnneeunivController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020relation\u0020\u00E9tudiant\u0020\/\u0020ann\u00E9e\u0020de\u0020formation\u0020\/\u0020ann\u00E9e\u0020universitaire",
            "url": "classes/App-Http-Controllers-EtudiantAnneeformAnneeunivController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantAnneeformAnneeunivController\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "Retourne\u0020les\u0020relations\u0020selon\u0020des\u0020crit\u00E8res\u0020de\u0020filtrage",
            "url": "classes/App-Http-Controllers-EtudiantAnneeformAnneeunivController.html#method_filter"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantAnneeformAnneeunivController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020relation\u0020\u00E9tudiant\u0020\/\u0020ann\u00E9e\u0020de\u0020formation\u0020\/\u0020ann\u00E9e\u0020universitaire",
            "url": "classes/App-Http-Controllers-EtudiantAnneeformAnneeunivController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController",
            "name": "EtudiantController",
            "summary": "",
            "url": "classes/App-Http-Controllers-EtudiantController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020tous\u0020les\u0020\u00E9tudiants",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003AindexRechercheStage\u0028\u0029",
            "name": "indexRechercheStage",
            "summary": "Retourne\u0020toutes\u0020les\u0020recherches\u0020de\u0020stage\u0020d\u0027un\u0020\u00E9tudiant\u0020donn\u00E9\nCode\u0020HTTP\u0020retourn\u00E9\u0020\u003A\n\u0020\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020200\u0020\u003A\u0020si\u0020l\u0027\u00E9tudiant\u0020a\u0020\u00E9t\u00E9\u0020trouv\u00E9\u0020et\u0020qu\u0027il\u0020a\u0020des\u0020recherches\u0020de\u0020stage\n\u0020\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020404\u0020\u003A\u0020si\u0020l\u0027\u00E9tudiant\u0020a\u0020\u00E9t\u00E9\u0020trouv\u00E9\u0020mais\u0020qu\u0027il\u0020n\u0027a\u0020pas\u0020de\u0020recherche\u0020de\u0020stage\u0020ou\u0020si\u0020l\u0027\u00E9tudiant\u0020n\u0027a\u0020pas\u0020\u00E9t\u00E9\u0020trouv\u00E9\n\u0020\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020500\u0020\u003A\u0020s\u0027il\u0020y\u0020a\u0020une\u0020erreur",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_indexRechercheStage"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003AindexFicheDescriptive\u0028\u0029",
            "name": "indexFicheDescriptive",
            "summary": "Retourne\u0020toutes\u0020les\u0020recherches\u0020de\u0020stage\u0020d\u0027un\u0020\u00E9tudiant\u0020donn\u00E9\nCode\u0020HTTP\u0020retourn\u00E9\u0020\u003A\n\u0020\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020200\u0020\u003A\u0020si\u0020l\u0027\u00E9tudiant\u0020a\u0020\u00E9t\u00E9\u0020trouv\u00E9\u0020et\u0020qu\u0027il\u0020a\u0020des\u0020recherches\u0020de\u0020stage\n\u0020\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020404\u0020\u003A\u0020si\u0020l\u0027\u00E9tudiant\u0020a\u0020\u00E9t\u00E9\u0020trouv\u00E9\u0020mais\u0020qu\u0027il\u0020n\u0027a\u0020pas\u0020de\u0020recherche\u0020de\u0020stage\u0020ou\u0020si\u0020l\u0027\u00E9tudiant\u0020n\u0027a\u0020pas\u0020\u00E9t\u00E9\u0020trouv\u00E9\n\u0020\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020500\u0020\u003A\u0020s\u0027il\u0020y\u0020a\u0020une\u0020erreur",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_indexFicheDescriptive"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003AindexParcours\u0028\u0029",
            "name": "indexParcours",
            "summary": "Retourne\u0020toutes\u0020les\u0020informations\u0020du\u0020parcours\u0020de\u0020l\u0027\u00E9tudiant\u0020pass\u00E9\u0020en\u0020param\u00E8tre\nCode\u0020HTTP\u0020retourn\u00E9\u0020\u003A\n\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020200\u0020\u003A\u0020si\u0020l\u0027\u00E9tudiant\u0020a\u0020\u00E9t\u00E9\u0020trouv\u00E9\u0020et\u0020qu\u0027il\u0020a\u0020un\u0020parcours\n\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020404\u0020\u003A\u0020si\u0020l\u0027\u00E9tudiant\u0020a\u0020\u00E9t\u00E9\u0020trouv\u00E9\u0020mais\u0020qu\u0027il\u0020n\u0027a\u0020pas\u0020de\u0020parcours\u0020ou\u0020si\u0020l\u0027\u00E9tudiant\u0020n\u0027a\u0020pas\u0020\u00E9t\u00E9\u0020trouv\u00E9\n\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020500\u0020\u003A\u0020s\u0027il\u0020y\u0020a\u0020une\u0020erreur",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_indexParcours"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantController\u003A\u003AindexPromo\u0028\u0029",
            "name": "indexPromo",
            "summary": "Retourne\u0020toutes\u0020les\u0020informations\u0020du\u0020parcours\u0020de\u0020l\u0027\u00E9tudiant\u0020pass\u00E9\u0020en\u0020param\u00E8tre\nCode\u0020HTTP\u0020retourn\u00E9\u0020\u003A\n\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020200\u0020\u003A\u0020si\u0020l\u0027\u00E9tudiant\u0020a\u0020\u00E9t\u00E9\u0020trouv\u00E9\u0020et\u0020qu\u0027il\u0020a\u0020un\u0020parcours\n\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020404\u0020\u003A\u0020si\u0020l\u0027\u00E9tudiant\u0020a\u0020\u00E9t\u00E9\u0020trouv\u00E9\u0020mais\u0020qu\u0027il\u0020n\u0027a\u0020pas\u0020de\u0020parcours\u0020ou\u0020si\u0020l\u0027\u00E9tudiant\u0020n\u0027a\u0020pas\u0020\u00E9t\u00E9\u0020trouv\u00E9\n\u0020\u0020\u0020\u0020\u002D\u0020Code\u0020500\u0020\u003A\u0020s\u0027il\u0020y\u0020a\u0020une\u0020erreur",
            "url": "classes/App-Http-Controllers-EtudiantController.html#method_indexPromo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantTdAnneeUnivController",
            "name": "EtudiantTdAnneeUnivController",
            "summary": "",
            "url": "classes/App-Http-Controllers-EtudiantTdAnneeUnivController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantTdAnneeUnivController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020relations\u0020\u00E9tudiant\u0020\/\u0020TD\u0020\/\u0020ann\u00E9e\u0020universitaire",
            "url": "classes/App-Http-Controllers-EtudiantTdAnneeUnivController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantTdAnneeUnivController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020relation\u0020\u00E9tudiant\u0020\/\u0020TD\u0020\/\u0020ann\u00E9e\u0020universitaire",
            "url": "classes/App-Http-Controllers-EtudiantTdAnneeUnivController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantTdAnneeUnivController\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "Retourne\u0020les\u0020relations\u0020selon\u0020des\u0020crit\u00E8res\u0020de\u0020filtrage",
            "url": "classes/App-Http-Controllers-EtudiantTdAnneeUnivController.html#method_filter"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\EtudiantTdAnneeUnivController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020relation\u0020\u00E9tudiant\u0020\/\u0020TD\u0020\/\u0020ann\u00E9e\u0020universitaire",
            "url": "classes/App-Http-Controllers-EtudiantTdAnneeUnivController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\FicheDescriptiveController",
            "name": "FicheDescriptiveController",
            "summary": "",
            "url": "classes/App-Http-Controllers-FicheDescriptiveController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\FicheDescriptiveController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Enregistre\u0020les\u0020donn\u00E9es\u0020du\u0020formulaire\u0020d\u0027une\u0020fiche\u0020descriptive",
            "url": "classes/App-Http-Controllers-FicheDescriptiveController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\FicheDescriptiveController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Met\u0020\u00E0\u0020jour\u0020les\u0020donn\u00E9es\u0020d\u0027une\u0020fiche\u0020descriptive",
            "url": "classes/App-Http-Controllers-FicheDescriptiveController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\FicheDescriptiveController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020donn\u00E9es\u0020d\u0027une\u0020fiche\u0020descriptive",
            "url": "classes/App-Http-Controllers-FicheDescriptiveController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\FicheDescriptiveController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "R\u00E9cup\u00E8re\u0020l\u0027ensemble\u0020des\u0020fiches\u0020descriptives",
            "url": "classes/App-Http-Controllers-FicheDescriptiveController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\FicheDescriptiveController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020fiche\u0020descriptive",
            "url": "classes/App-Http-Controllers-FicheDescriptiveController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParcoursController",
            "name": "ParcoursController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ParcoursController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParcoursController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020tous\u0020les\u0020parcours",
            "url": "classes/App-Http-Controllers-ParcoursController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PersonnelController",
            "name": "PersonnelController",
            "summary": "",
            "url": "classes/App-Http-Controllers-PersonnelController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PersonnelController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020tous\u0020les\u0020membres\u0020du\u0020personnels\u0020existants",
            "url": "classes/App-Http-Controllers-PersonnelController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PersonnelController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020un\u0020nouveau\u0020membre\u0020du\u0020personnel",
            "url": "classes/App-Http-Controllers-PersonnelController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PersonnelController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020un\u0020membre\u0020du\u0020personnel\u0020particulier",
            "url": "classes/App-Http-Controllers-PersonnelController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PersonnelController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020un\u0020membre\u0020du\u0020personnel\u0020particulier",
            "url": "classes/App-Http-Controllers-PersonnelController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PersonnelController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020un\u0020membre\u0020du\u0020personnel\u0020particulier",
            "url": "classes/App-Http-Controllers-PersonnelController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController",
            "name": "PlanningController",
            "summary": "",
            "url": "classes/App-Http-Controllers-PlanningController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020tous\u0020les\u0020plannings",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020un\u0020nouveau\u0020planning",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020un\u0020planning\u0020particulier",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020un\u0020planning\u0020particulier",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020un\u0020planning\u0020particulier",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\RechercheStageController",
            "name": "RechercheStageController",
            "summary": "",
            "url": "classes/App-Http-Controllers-RechercheStageController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\RechercheStageController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020recherches\u0020de\u0020stage",
            "url": "classes/App-Http-Controllers-RechercheStageController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\RechercheStageController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020recherche\u0020de\u0020stage.",
            "url": "classes/App-Http-Controllers-RechercheStageController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\RechercheStageController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020une\u0020recherche\u0020de\u0020stage\u0020particulier",
            "url": "classes/App-Http-Controllers-RechercheStageController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\RechercheStageController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020une\u0020recherche\u0020de\u0020stage\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-RechercheStageController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\RechercheStageController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020recherche\u0020de\u0020stage\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-RechercheStageController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleController",
            "name": "SalleController",
            "summary": "",
            "url": "classes/App-Http-Controllers-SalleController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020salles",
            "url": "classes/App-Http-Controllers-SalleController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-SalleController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020salle",
            "url": "classes/App-Http-Controllers-SalleController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020une\u0020salle\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-SalleController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-SalleController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020une\u0020salle\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-SalleController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020salle\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-SalleController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController",
            "name": "SoutenanceController",
            "summary": "",
            "url": "classes/App-Http-Controllers-SoutenanceController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020toutes\u0020les\u0020soutenances",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020une\u0020nouvelle\u0020soutenance",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003AstoreMany\u0028\u0029",
            "name": "storeMany",
            "summary": "Cr\u00E9e\u0020plusieurs\u0020soutenances\u0020en\u0020une\u0020seule\u0020requ\u00EAte",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_storeMany"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020une\u0020soutenance\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020une\u0020soutenance\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003AupdateMany\u0028\u0029",
            "name": "updateMany",
            "summary": "Modifie\u0020plusieurs\u0020soutenances\u0020en\u0020une\u0020seule\u0020requ\u00EAte",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_updateMany"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SoutenanceController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020soutenance\u0020particuli\u00E8re",
            "url": "classes/App-Http-Controllers-SoutenanceController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TDController",
            "name": "TDController",
            "summary": "",
            "url": "classes/App-Http-Controllers-TDController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TDController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020tous\u0020les\u0020TD",
            "url": "classes/App-Http-Controllers-TDController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TDController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020un\u0020nouveau\u0020TD",
            "url": "classes/App-Http-Controllers-TDController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TDController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Retourne\u0020un\u0020TD\u0020particulier",
            "url": "classes/App-Http-Controllers-TDController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TDController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020un\u0020TD\u0020particulier",
            "url": "classes/App-Http-Controllers-TDController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TDController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020un\u0020TD\u0020particulier",
            "url": "classes/App-Http-Controllers-TDController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TuteurEntrepriseController",
            "name": "TuteurEntrepriseController",
            "summary": "",
            "url": "classes/App-Http-Controllers-TuteurEntrepriseController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TuteurEntrepriseController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retourne\u0020tous\u0020les\u0020tuteurs\u0020d\u0027entreprise",
            "url": "classes/App-Http-Controllers-TuteurEntrepriseController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TuteurEntrepriseController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Renvoie\u0020un\u0020tuteur\u0020d\u0027entreprise\u0020particulier",
            "url": "classes/App-Http-Controllers-TuteurEntrepriseController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TuteurEntrepriseController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Cr\u00E9er\u0020un\u0020nouveau\u0020tuteur\u0020d\u0027entreprise",
            "url": "classes/App-Http-Controllers-TuteurEntrepriseController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TuteurEntrepriseController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Met\u0020\u00E0\u0020jour\u0020un\u0020tuteur\u0020particulier",
            "url": "classes/App-Http-Controllers-TuteurEntrepriseController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Http-Kernel.html"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middleware",
            "name": "middleware",
            "summary": "The\u0020application\u0027s\u0020global\u0020HTTP\u0020middleware\u0020stack.",
            "url": "classes/App-Http-Kernel.html#property_middleware"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middlewareGroups",
            "name": "middlewareGroups",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware\u0020groups.",
            "url": "classes/App-Http-Kernel.html#property_middlewareGroups"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024routeMiddleware",
            "name": "routeMiddleware",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware.",
            "url": "classes/App-Http-Kernel.html#property_routeMiddleware"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate",
            "name": "Authenticate",
            "summary": "",
            "url": "classes/App-Http-Middleware-Authenticate.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate\u003A\u003AredirectTo\u0028\u0029",
            "name": "redirectTo",
            "summary": "Get\u0020the\u0020path\u0020the\u0020user\u0020should\u0020be\u0020redirected\u0020to\u0020when\u0020they\u0020are\u0020not\u0020authenticated.",
            "url": "classes/App-Http-Middleware-Authenticate.html#method_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\CasAuthMiddleware",
            "name": "CasAuthMiddleware",
            "summary": "",
            "url": "classes/App-Http-Middleware-CasAuthMiddleware.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\CasAuthMiddleware\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "G\u00E8re\u0020la\u0020requ\u00EAte\u0020entrante\u0020et\u0020l\u0027authentification\u0020CAS.",
            "url": "classes/App-Http-Middleware-CasAuthMiddleware.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\CasAuthMiddleware\u003A\u003AhandleCookieLogout\u0028\u0029",
            "name": "handleCookieLogout",
            "summary": "G\u00E8re\u0020uniquement\u0020la\u0020suppression\u0020des\u0020cookies\u0020d\u0027authentification.",
            "url": "classes/App-Http-Middleware-CasAuthMiddleware.html#method_handleCookieLogout"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\CasAuthMiddleware\u003A\u003AhandleCasLogout\u0028\u0029",
            "name": "handleCasLogout",
            "summary": "G\u00E8re\u0020la\u0020d\u00E9connexion\u0020du\u0020CAS\u0020uniquement.",
            "url": "classes/App-Http-Middleware-CasAuthMiddleware.html#method_handleCasLogout"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\DispatchDataDescriptiveSheet",
            "name": "DispatchDataDescriptiveSheet",
            "summary": "",
            "url": "classes/App-Http-Middleware-DispatchDataDescriptiveSheet.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\DispatchDataDescriptiveSheet\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-DispatchDataDescriptiveSheet.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\DispatchDataDescriptiveSheet\u003A\u003AhandleSheetCreation\u0028\u0029",
            "name": "handleSheetCreation",
            "summary": "Cr\u00E9ation\u0020d\u0027une\u0020fiche\u0020descriptive.",
            "url": "classes/App-Http-Middleware-DispatchDataDescriptiveSheet.html#method_handleSheetCreation"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\DispatchDataDescriptiveSheet\u003A\u003AhandleSheetUpdate\u0028\u0029",
            "name": "handleSheetUpdate",
            "summary": "Mise\u0020\u00E0\u0020jour\u0020de\u0020la\u0020fiche\u0020descriptive.",
            "url": "classes/App-Http-Middleware-DispatchDataDescriptiveSheet.html#method_handleSheetUpdate"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\DispatchDataDescriptiveSheet\u003A\u003AhandleSheetGet\u0028\u0029",
            "name": "handleSheetGet",
            "summary": "R\u00E9cup\u00E9ration\u0020d\u0027une\u0020fiche\u0020descriptive.",
            "url": "classes/App-Http-Middleware-DispatchDataDescriptiveSheet.html#method_handleSheetGet"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\DispatchDataDescriptiveSheet\u003A\u003A\u0024mapping",
            "name": "mapping",
            "summary": "",
            "url": "classes/App-Http-Middleware-DispatchDataDescriptiveSheet.html#property_mapping"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies",
            "name": "EncryptCookies",
            "summary": "",
            "url": "classes/App-Http-Middleware-EncryptCookies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020cookies\u0020that\u0020should\u0020not\u0020be\u0020encrypted.",
            "url": "classes/App-Http-Middleware-EncryptCookies.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "name": "PreventRequestsDuringMaintenance",
            "summary": "",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020reachable\u0020while\u0020maintenance\u0020mode\u0020is\u0020enabled.",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated",
            "name": "RedirectIfAuthenticated",
            "summary": "",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings",
            "name": "TrimStrings",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrimStrings.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020attributes\u0020that\u0020should\u0020not\u0020be\u0020trimmed.",
            "url": "classes/App-Http-Middleware-TrimStrings.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts",
            "name": "TrustHosts",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustHosts.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts\u003A\u003Ahosts\u0028\u0029",
            "name": "hosts",
            "summary": "Get\u0020the\u0020host\u0020patterns\u0020that\u0020should\u0020be\u0020trusted.",
            "url": "classes/App-Http-Middleware-TrustHosts.html#method_hosts"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies",
            "name": "TrustProxies",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustProxies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024proxies",
            "name": "proxies",
            "summary": "The\u0020trusted\u0020proxies\u0020for\u0020this\u0020application.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_proxies"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "The\u0020headers\u0020that\u0020should\u0020be\u0020used\u0020to\u0020detect\u0020proxies.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_headers"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken",
            "name": "VerifyCsrfToken",
            "summary": "",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020excluded\u0020from\u0020CSRF\u0020verification.",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html#property_except"
        },                {
            "fqsen": "\\App\\Models\\AnneeFormation",
            "name": "AnneeFormation",
            "summary": "",
            "url": "classes/App-Models-AnneeFormation.html"
        },                {
            "fqsen": "\\App\\Models\\AnneeFormation\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-AnneeFormation.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\AnneeFormation\u003A\u003AanneeUniversitaires\u0028\u0029",
            "name": "anneeUniversitaires",
            "summary": "",
            "url": "classes/App-Models-AnneeFormation.html#method_anneeUniversitaires"
        },                {
            "fqsen": "\\App\\Models\\AnneeFormation\u003A\u003Aplannings\u0028\u0029",
            "name": "plannings",
            "summary": "",
            "url": "classes/App-Models-AnneeFormation.html#method_plannings"
        },                {
            "fqsen": "\\App\\Models\\AnneeFormation\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-AnneeFormation.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\AnneeFormation\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-AnneeFormation.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\AnneeFormation\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-AnneeFormation.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire",
            "name": "AnneeUniversitaire",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003AanneeFormations\u0028\u0029",
            "name": "anneeFormations",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#method_anneeFormations"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003Aparcours\u0028\u0029",
            "name": "parcours",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#method_parcours"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003Apersonnels\u0028\u0029",
            "name": "personnels",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#method_personnels"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003Atds\u0028\u0029",
            "name": "tds",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#method_tds"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003Atps\u0028\u0029",
            "name": "tps",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#method_tps"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\AnneeUniversitaire\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-AnneeUniversitaire.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\DepartementIUT",
            "name": "DepartementIUT",
            "summary": "",
            "url": "classes/App-Models-DepartementIUT.html"
        },                {
            "fqsen": "\\App\\Models\\DepartementIUT\u003A\u003Aparcours\u0028\u0029",
            "name": "parcours",
            "summary": "",
            "url": "classes/App-Models-DepartementIUT.html#method_parcours"
        },                {
            "fqsen": "\\App\\Models\\DepartementIUT\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-DepartementIUT.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\DepartementIUT\u003A\u003Apersonnels\u0028\u0029",
            "name": "personnels",
            "summary": "",
            "url": "classes/App-Models-DepartementIUT.html#method_personnels"
        },                {
            "fqsen": "\\App\\Models\\DepartementIUT\u003A\u003Aroles\u0028\u0029",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Models-DepartementIUT.html#method_roles"
        },                {
            "fqsen": "\\App\\Models\\DepartementIUT\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-DepartementIUT.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\DepartementIUT\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-DepartementIUT.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\DepartementIUT\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-DepartementIUT.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Entreprise",
            "name": "Entreprise",
            "summary": "",
            "url": "classes/App-Models-Entreprise.html"
        },                {
            "fqsen": "\\App\\Models\\Entreprise\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-Entreprise.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\Entreprise\u003A\u003AficheDescriptives\u0028\u0029",
            "name": "ficheDescriptives",
            "summary": "",
            "url": "classes/App-Models-Entreprise.html#method_ficheDescriptives"
        },                {
            "fqsen": "\\App\\Models\\Entreprise\u003A\u003AtuteurEntreprises\u0028\u0029",
            "name": "tuteurEntreprises",
            "summary": "",
            "url": "classes/App-Models-Entreprise.html#method_tuteurEntreprises"
        },                {
            "fqsen": "\\App\\Models\\Entreprise\u003A\u003ArechercheStages\u0028\u0029",
            "name": "rechercheStages",
            "summary": "",
            "url": "classes/App-Models-Entreprise.html#method_rechercheStages"
        },                {
            "fqsen": "\\App\\Models\\Entreprise\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Entreprise.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Entreprise\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Entreprise.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Entreprise\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Entreprise.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Etudiant",
            "name": "Etudiant",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003AdepartementIUT\u0028\u0029",
            "name": "departementIUT",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_departementIUT"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003Aentreprise\u0028\u0029",
            "name": "entreprise",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_entreprise"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003AficheDescriptives\u0028\u0029",
            "name": "ficheDescriptives",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_ficheDescriptives"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003ArechercheStages\u0028\u0029",
            "name": "rechercheStages",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_rechercheStages"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003AtuteurEntreprise\u0028\u0029",
            "name": "tuteurEntreprise",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_tuteurEntreprise"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003Aparcours\u0028\u0029",
            "name": "parcours",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_parcours"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003Apersonnels\u0028\u0029",
            "name": "personnels",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_personnels"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003Atps\u0028\u0029",
            "name": "tps",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_tps"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003Atds\u0028\u0029",
            "name": "tds",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_tds"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003AanneeFormations\u0028\u0029",
            "name": "anneeFormations",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_anneeFormations"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003AanneeUniversitaires\u0028\u0029",
            "name": "anneeUniversitaires",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_anneeUniversitaires"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003Asoutenances\u0028\u0029",
            "name": "soutenances",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#method_soutenances"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#property_incrementing"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Etudiant\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "",
            "url": "classes/App-Models-Etudiant.html#property_casts"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv",
            "name": "EtudiantAnneeformAnneeuniv",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv\u003A\u003Aetudiant\u0028\u0029",
            "name": "etudiant",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html#method_etudiant"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv\u003A\u003AanneeFormation\u0028\u0029",
            "name": "anneeFormation",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html#method_anneeFormation"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv\u003A\u003AanneeUniversitaire\u0028\u0029",
            "name": "anneeUniversitaire",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html#method_anneeUniversitaire"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html#property_incrementing"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\EtudiantAnneeformAnneeuniv\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-EtudiantAnneeformAnneeuniv.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv",
            "name": "EtudiantTdAnneeUniv",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv\u003A\u003Aetudiant\u0028\u0029",
            "name": "etudiant",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html#method_etudiant"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv\u003A\u003Atd\u0028\u0029",
            "name": "td",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html#method_td"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv\u003A\u003AanneeUniversitaire\u0028\u0029",
            "name": "anneeUniversitaire",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html#method_anneeUniversitaire"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html#property_incrementing"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\EtudiantTdAnneeUniv\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-EtudiantTdAnneeUniv.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\FicheDescriptive",
            "name": "FicheDescriptive",
            "summary": "",
            "url": "classes/App-Models-FicheDescriptive.html"
        },                {
            "fqsen": "\\App\\Models\\FicheDescriptive\u003A\u003Aentreprise\u0028\u0029",
            "name": "entreprise",
            "summary": "",
            "url": "classes/App-Models-FicheDescriptive.html#method_entreprise"
        },                {
            "fqsen": "\\App\\Models\\FicheDescriptive\u003A\u003AtuteurEntreprise\u0028\u0029",
            "name": "tuteurEntreprise",
            "summary": "",
            "url": "classes/App-Models-FicheDescriptive.html#method_tuteurEntreprise"
        },                {
            "fqsen": "\\App\\Models\\FicheDescriptive\u003A\u003Aetudiant\u0028\u0029",
            "name": "etudiant",
            "summary": "",
            "url": "classes/App-Models-FicheDescriptive.html#method_etudiant"
        },                {
            "fqsen": "\\App\\Models\\FicheDescriptive\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-FicheDescriptive.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\FicheDescriptive\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-FicheDescriptive.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\FicheDescriptive\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-FicheDescriptive.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Parcours",
            "name": "Parcours",
            "summary": "",
            "url": "classes/App-Models-Parcours.html"
        },                {
            "fqsen": "\\App\\Models\\Parcours\u003A\u003AdepartementIUT\u0028\u0029",
            "name": "departementIUT",
            "summary": "",
            "url": "classes/App-Models-Parcours.html#method_departementIUT"
        },                {
            "fqsen": "\\App\\Models\\Parcours\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-Parcours.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\Parcours\u003A\u003AanneeUniversitaires\u0028\u0029",
            "name": "anneeUniversitaires",
            "summary": "",
            "url": "classes/App-Models-Parcours.html#method_anneeUniversitaires"
        },                {
            "fqsen": "\\App\\Models\\Parcours\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Parcours.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Parcours\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Parcours.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Parcours\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Parcours.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Parcours\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/App-Models-Parcours.html#property_incrementing"
        },                {
            "fqsen": "\\App\\Models\\Parcours\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Parcours.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Personnel",
            "name": "Personnel",
            "summary": "",
            "url": "classes/App-Models-Personnel.html"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003Aadmins\u0028\u0029",
            "name": "admins",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#method_admins"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003Adroits\u0028\u0029",
            "name": "droits",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#method_droits"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003AdepartementIUTs\u0028\u0029",
            "name": "departementIUTs",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#method_departementIUTs"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003Aroles\u0028\u0029",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#method_roles"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003Asoutenances\u0028\u0029",
            "name": "soutenances",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#method_soutenances"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Personnel\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Personnel.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Planning",
            "name": "Planning",
            "summary": "",
            "url": "classes/App-Models-Planning.html"
        },                {
            "fqsen": "\\App\\Models\\Planning\u003A\u003AanneeFormation\u0028\u0029",
            "name": "anneeFormation",
            "summary": "",
            "url": "classes/App-Models-Planning.html#method_anneeFormation"
        },                {
            "fqsen": "\\App\\Models\\Planning\u003A\u003AanneeUniversitaire\u0028\u0029",
            "name": "anneeUniversitaire",
            "summary": "",
            "url": "classes/App-Models-Planning.html#method_anneeUniversitaire"
        },                {
            "fqsen": "\\App\\Models\\Planning\u003A\u003Asalles\u0028\u0029",
            "name": "salles",
            "summary": "",
            "url": "classes/App-Models-Planning.html#method_salles"
        },                {
            "fqsen": "\\App\\Models\\Planning\u003A\u003Asoutenances\u0028\u0029",
            "name": "soutenances",
            "summary": "",
            "url": "classes/App-Models-Planning.html#method_soutenances"
        },                {
            "fqsen": "\\App\\Models\\Planning\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Planning.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Planning\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Planning.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Planning\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Planning.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\RechercheStage",
            "name": "RechercheStage",
            "summary": "",
            "url": "classes/App-Models-RechercheStage.html"
        },                {
            "fqsen": "\\App\\Models\\RechercheStage\u003A\u003Aetudiant\u0028\u0029",
            "name": "etudiant",
            "summary": "",
            "url": "classes/App-Models-RechercheStage.html#method_etudiant"
        },                {
            "fqsen": "\\App\\Models\\RechercheStage\u003A\u003Aentreprise\u0028\u0029",
            "name": "entreprise",
            "summary": "",
            "url": "classes/App-Models-RechercheStage.html#method_entreprise"
        },                {
            "fqsen": "\\App\\Models\\RechercheStage\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-RechercheStage.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\RechercheStage\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-RechercheStage.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\RechercheStage\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-RechercheStage.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Role",
            "name": "Role",
            "summary": "",
            "url": "classes/App-Models-Role.html"
        },                {
            "fqsen": "\\App\\Models\\Role\u003A\u003Apersonnels\u0028\u0029",
            "name": "personnels",
            "summary": "",
            "url": "classes/App-Models-Role.html#method_personnels"
        },                {
            "fqsen": "\\App\\Models\\Role\u003A\u003Adepartementiuts\u0028\u0029",
            "name": "departementiuts",
            "summary": "",
            "url": "classes/App-Models-Role.html#method_departementiuts"
        },                {
            "fqsen": "\\App\\Models\\Role\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Role.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Role\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Role.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Role\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Role.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Salle",
            "name": "Salle",
            "summary": "",
            "url": "classes/App-Models-Salle.html"
        },                {
            "fqsen": "\\App\\Models\\Salle\u003A\u003Aplannings\u0028\u0029",
            "name": "plannings",
            "summary": "",
            "url": "classes/App-Models-Salle.html#method_plannings"
        },                {
            "fqsen": "\\App\\Models\\Salle\u003A\u003Asoutenances\u0028\u0029",
            "name": "soutenances",
            "summary": "",
            "url": "classes/App-Models-Salle.html#method_soutenances"
        },                {
            "fqsen": "\\App\\Models\\Salle\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Salle.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Salle\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Salle.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Salle\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/App-Models-Salle.html#property_incrementing"
        },                {
            "fqsen": "\\App\\Models\\Salle\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Salle.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Soutenance",
            "name": "Soutenance",
            "summary": "",
            "url": "classes/App-Models-Soutenance.html"
        },                {
            "fqsen": "\\App\\Models\\Soutenance\u003A\u003Aplanning\u0028\u0029",
            "name": "planning",
            "summary": "",
            "url": "classes/App-Models-Soutenance.html#method_planning"
        },                {
            "fqsen": "\\App\\Models\\Soutenance\u003A\u003Asalle\u0028\u0029",
            "name": "salle",
            "summary": "",
            "url": "classes/App-Models-Soutenance.html#method_salle"
        },                {
            "fqsen": "\\App\\Models\\Soutenance\u003A\u003Aetudiant\u0028\u0029",
            "name": "etudiant",
            "summary": "",
            "url": "classes/App-Models-Soutenance.html#method_etudiant"
        },                {
            "fqsen": "\\App\\Models\\Soutenance\u003A\u003Apersonnel\u0028\u0029",
            "name": "personnel",
            "summary": "",
            "url": "classes/App-Models-Soutenance.html#method_personnel"
        },                {
            "fqsen": "\\App\\Models\\Soutenance\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Soutenance.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Soutenance\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Soutenance.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Soutenance\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Soutenance.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\TD",
            "name": "TD",
            "summary": "",
            "url": "classes/App-Models-TD.html"
        },                {
            "fqsen": "\\App\\Models\\TD\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-TD.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\TD\u003A\u003AanneeUniversitaires\u0028\u0029",
            "name": "anneeUniversitaires",
            "summary": "",
            "url": "classes/App-Models-TD.html#method_anneeUniversitaires"
        },                {
            "fqsen": "\\App\\Models\\TD\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-TD.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\TD\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-TD.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\TD\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-TD.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\TD\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-TD.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\TP",
            "name": "TP",
            "summary": "",
            "url": "classes/App-Models-TP.html"
        },                {
            "fqsen": "\\App\\Models\\TP\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-TP.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\TP\u003A\u003AanneeUniversitaires\u0028\u0029",
            "name": "anneeUniversitaires",
            "summary": "",
            "url": "classes/App-Models-TP.html#method_anneeUniversitaires"
        },                {
            "fqsen": "\\App\\Models\\TP\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-TP.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\TP\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-TP.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\TP\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-TP.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\TP\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-TP.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\TuteurEntreprise",
            "name": "TuteurEntreprise",
            "summary": "",
            "url": "classes/App-Models-TuteurEntreprise.html"
        },                {
            "fqsen": "\\App\\Models\\TuteurEntreprise\u003A\u003AficheDescriptives\u0028\u0029",
            "name": "ficheDescriptives",
            "summary": "",
            "url": "classes/App-Models-TuteurEntreprise.html#method_ficheDescriptives"
        },                {
            "fqsen": "\\App\\Models\\TuteurEntreprise\u003A\u003Aentreprise\u0028\u0029",
            "name": "entreprise",
            "summary": "",
            "url": "classes/App-Models-TuteurEntreprise.html#method_entreprise"
        },                {
            "fqsen": "\\App\\Models\\TuteurEntreprise\u003A\u003Aetudiants\u0028\u0029",
            "name": "etudiants",
            "summary": "",
            "url": "classes/App-Models-TuteurEntreprise.html#method_etudiants"
        },                {
            "fqsen": "\\App\\Models\\TuteurEntreprise\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-TuteurEntreprise.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\TuteurEntreprise\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-TuteurEntreprise.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\TuteurEntreprise\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-TuteurEntreprise.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#property_casts"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider",
            "name": "AuthServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AuthServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020authentication\u0020\/\u0020authorization\u0020services.",
            "url": "classes/App-Providers-AuthServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003A\u0024policies",
            "name": "policies",
            "summary": "The\u0020policy\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-AuthServiceProvider.html#property_policies"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider",
            "name": "BroadcastServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-BroadcastServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-BroadcastServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider",
            "name": "EventServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-EventServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020events\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003A\u0024listen",
            "name": "listen",
            "summary": "The\u0020event\u0020listener\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#property_listen"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider",
            "name": "RouteServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-RouteServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Define\u0020your\u0020route\u0020model\u0020bindings,\u0020pattern\u0020filters,\u0020etc.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AconfigureRateLimiting\u0028\u0029",
            "name": "configureRateLimiting",
            "summary": "Configure\u0020the\u0020rate\u0020limiters\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_configureRateLimiting"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AHOME",
            "name": "HOME",
            "summary": "The\u0020path\u0020to\u0020the\u0020\u0022home\u0022\u0020route\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-RouteServiceProvider.html#constant_HOME"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App\\Exports",
            "name": "Exports",
            "summary": "",
            "url": "namespaces/app-exports.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        }            ]
);
